name: bloc_sample
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  intl: ^0.18.1
  dio: ^5.4.2
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

#  fonts:
#
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Inter-Light.ttf
#          weight: 300
#        - asset: assets/fonts/Inter-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Inter-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Inter-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Inter-Bold.ttf
#          weight: 700

